# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [8]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [9]:
chipo = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv', sep='\t')
chipo.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

### Step 4. How many products cost more than $10.00?

In [10]:
chipo['item_price'] = chipo['item_price'].apply(lambda x: float(x[1:]))

In [ ]:
# solution 1
count = chipo['item_price'].apply(lambda x: 1 if x > 10 else 0)
count.sum()

np.int64(1130)

In [37]:
# solution 2
(chipo['item_price'] > 10).sum()

np.int64(1130)

### Step 5. What is the price of each item? 
###### print a data frame with only three columns item_name choice_description and product_price

In [ ]:
# solution 1 "this print the three columns whithout any modifation"
item_prices = chipo[['item_name', 'choice_description', 'item_price']]
item_prices.head(10)

,item_name,choice_description,item_price
0,Chips and Fresh Tomato Salsa,NaN,2.39
1,Izze,[Clementine],3.39
2,Nantucket Nectar,[Apple],3.39
3,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
5,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98
6,Side of Chips,NaN,1.69
7,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75
8,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",9.25
9,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",9.25

In [ ]:
# solution 2 "this print the mean price for each unique item"
item_prices = chipo.groupby(['item_name', 'choice_description'])[['item_price']].mean()
item_prices.head(10)

                                                                      item_price
item_name         choice_description
6 Pack Soft Drink [Coke]                                                6.490000
                  [Diet Coke]                                           6.760417
                  [Lemonade]                                            6.490000
                  [Nestea]                                              6.490000
                  [Sprite]                                              6.490000
Barbacoa Bowl     [Fresh Tomato (Mild), [Lettuce, Black Beans, Ri...    8.690000
                  [Fresh Tomato (Mild), [Lettuce, Rice, Cheese]]        8.690000
                  [Fresh Tomato Salsa (Mild), [Black Beans, Rice,...   11.480000
                  [Fresh Tomato Salsa (Mild), [Rice, Cheese, Sour...    8.990000
                  [Fresh Tomato Salsa, [Fajita Vegetables, Rice, ...   11.750000

### Step 6. Sort by the name of the item

In [ ]:
# this dorted the items by name without take the mean price "just sort"
item_prices = chipo[['item_name', 'choice_description', 'item_price']]
item_prices = item_prices.sort_values(by='item_name')
item_prices.head(10)

              item_name choice_description  item_price
3389  6 Pack Soft Drink        [Diet Coke]       12.98
341   6 Pack Soft Drink        [Diet Coke]        6.49
1849  6 Pack Soft Drink             [Coke]        6.49
1860  6 Pack Soft Drink        [Diet Coke]        6.49
2713  6 Pack Soft Drink             [Coke]        6.49
3422  6 Pack Soft Drink             [Coke]        6.49
553   6 Pack Soft Drink        [Diet Coke]        6.49
1916  6 Pack Soft Drink        [Diet Coke]        6.49
1922  6 Pack Soft Drink             [Coke]        6.49
1937  6 Pack Soft Drink        [Diet Coke]        6.49

### Step 7. What was the quantity of the most expensive item ordered?

In [ ]:
# solution 1
expensive_item = chipo['item_price'].max()
chipo[chipo['item_price'] == expensive_item]['quantity'].iloc[0]

np.int64(15)

In [50]:
# solution 2
chipo.loc[chipo['item_price'].idxmax(), 'quantity']

np.int64(15)

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [44]:
# solution 1
(chipo['item_name'] == 'Veggie Salad Bowl').sum()

np.int64(18)

In [43]:
# solution 2
chipo[chipo['item_name'] == 'Veggie Salad Bowl'].shape[0]

18

### Step 9. How many times did someone order more than one Canned Soda?

In [53]:
ordered_soda = chipo[chipo['item_name'] == 'Canned Soda']
ordered_soda[ordered_soda['quantity'] > 1].shape[0]

20